[2025-08-04T21:33:52.235+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_dag.fetch_and_store_stock_data scheduled__2025-08-04T20:00:00+00:00 [queued]>
[2025-08-04T21:33:52.415+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_dag.fetch_and_store_stock_data scheduled__2025-08-04T20:00:00+00:00 [queued]>
[2025-08-04T21:33:52.423+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2025-08-04T21:33:52.788+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): fetch_and_store_stock_data> on 2025-08-04 20:00:00+00:00
[2025-08-04T21:33:53.062+0000] {standard_task_runner.py:60} INFO - Started process 233 to run task
[2025-08-04T21:33:53.167+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'stock_data_dag', 'fetch_and_store_stock_data', 'scheduled__2025-08-04T20:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/stock_data_dag.py', '--cfg-path', '/tmp/tmpek53o40e']
[2025-08-04T21:33:53.306+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask fetch_and_store_stock_data
[2025-08-04T21:33:54.773+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_data_dag.fetch_and_store_stock_data scheduled__2025-08-04T20:00:00+00:00 [running]> on host 774479e86811
[2025-08-04T21:33:56.360+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_data_dag' AIRFLOW_CTX_TASK_ID='fetch_and_store_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-04T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-04T20:00:00+00:00'
[2025-08-04T21:33:59.552+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stock_data_dag.py", line 44, in fetch_and_store_stock_data
    redis_client.set(f"{ticker}_latest", json.dumps(transformed[:10]))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ObjectId is not JSON serializable
[2025-08-04T21:33:59.563+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_data_dag, task_id=fetch_and_store_stock_data, execution_date=20250804T200000, start_date=20250804T213352, end_date=20250804T213359
[2025-08-04T21:33:59.577+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task fetch_and_store_stock_data (Object of type ObjectId is not JSON serializable; 233)
[2025-08-04T21:33:59.611+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-04T21:33:59.641+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
